from .usuario import Usuario as UsuarioResource
from .usuario import Usuarios as UsuariosResource
from .usuario import UsuarioAlumno as UsuarioAlumnoResource
from .usuario import UsuariosAlumnos as UsuariosAlumnosResource
from .usuario import UsuarioProfesor as UsuarioProfesorResource
from .usuario import UsuariosProfesores as UsuariosProfesoresResource
from .planificacion import Planificacion as PlanificacionResource
from .planificacion import Planificaciones as PlanificacionesResource
from .planificacion import PlanificacionAlumno as PlanificacionAlumnoResource
from .planificacion import PlanificacionProfesor as PlanificacionProfesorResource
from .planificacion import PlanificacionesProfesores as PlanificacionesProfesoresResource
from .clases import Clase as ClaseResource
from .clases import Clases as ClasesResource
from .permiso import Permiso as PermisoResource
from .permiso import Permisos as PermisosResource
#from .pago import Pago as PagoResource
#from .login import Login as LoginResource