"""empty message

Revision ID: f83a9649f33b
Revises: 
Create Date: 2023-05-18 19:33:31.188722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f83a9649f33b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_index('ix_usuario_rol')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.create_index('ix_usuario_rol', ['rol'], unique=False)

    # ### end Alembic commands ###
